export const seedData = {
  departments: [
    { id: 'DEP-1', name: 'Engineering', head: 'Aditi Rao', parent: '-', employees: 42, status: 'Active' },
    { id: 'DEP-2', name: 'Facilities', head: 'Rohan Mehta', parent: '-', employees: 18, status: 'Active' },
    { id: 'DEP-7', name: 'Field Operations', head: 'Sana Iqbal', parent: '-', employees: 26, status: 'Active' },
    { id: 'DEP-4', name: 'Design', head: 'Arjun Nair', parent: '-', employees: 12, status: 'Active' },
    { id: 'DEP-5', name: 'Operations', head: 'S. Kapoor', parent: '-', employees: 9, status: 'Active' },
    { id: 'DEP-6', name: 'Unassigned', head: '-', parent: '-', employees: 0, status: 'Active' },
  ],
  categories: [
    { id: 'CAT-1', name: 'Electronics', count: 64, status: 'Active' },
    { id: 'CAT-2', name: 'Furniture', count: 38, status: 'Active' },
    { id: 'CAT-3', name: 'Vehicle', count: 12, status: 'Active' },
    { id: 'CAT-4', name: 'Appliance', count: 6, status: 'Active' },
    { id: 'CAT-5', name: 'Equipment', count: 8, status: 'Active' },
  ],
  employees: [
    { id: 'EMP-1', name: 'Priya Shah', department: 'Engineering', email: 'priya@assetflow.local', userId: null, role: 'employee', status: 'Active' },
    { id: 'EMP-2', name: 'Arjun Nair', department: 'Design', email: 'arjun@assetflow.local', userId: null, role: 'department_head', status: 'Active' },
    { id: 'EMP-3', name: 'Rohan Mehta', department: 'Facilities', email: 'rohan@assetflow.local', userId: null, role: 'asset_manager', status: 'Active' },
    { id: 'EMP-4', name: 'R. Varma', department: 'Operations', email: 'r.varma@assetflow.local', userId: null, role: 'employee', status: 'Active' },
    { id: 'EMP-5', name: 'S. Kapoor', department: 'Facilities', email: 's.kapoor@assetflow.local', userId: null, role: 'employee', status: 'Active' },
  ],
  assets: [
    { id: 'AF-0012', name: 'Dell Latitude', category: 'Electronics', status: 'Allocated', department: 'Engineering', location: 'Bengaluru', owner: 'Priya Shah', updated: '2h ago' },
    { id: 'AF-0062', name: 'Epson Projector', category: 'Electronics', status: 'Maintenance', department: 'Facilities', location: 'HQ Floor 2', owner: '-', updated: '1d ago' },
    { id: 'AF-0201', name: 'Ergo Office Chair', category: 'Furniture', status: 'Available', department: 'Unassigned', location: 'Warehouse', owner: '-', updated: '3d ago' },
    { id: 'AF-0114', name: 'MacBook Pro 14', category: 'Electronics', status: 'Allocated', department: 'Design', location: 'Mumbai', owner: 'Arjun Nair', updated: '5h ago' },
    { id: 'AF-0343', name: 'Tata Ace Van', category: 'Vehicle', status: 'Available', department: 'Field Operations', location: 'Pune Depot', owner: '-', updated: '1d ago' },
    { id: 'AF-0031', name: 'AC Unit', category: 'Appliance', status: 'Maintenance', department: 'Facilities', location: 'HQ Floor 1', owner: '-', updated: '4h ago' },
    { id: 'AF-0038', name: 'Forklift', category: 'Equipment', status: 'Maintenance', department: 'Operations', location: 'Warehouse', owner: 'R. Varma', updated: 'Today' },
    { id: 'AF-0007', name: 'Office Printer', category: 'Electronics', status: 'Maintenance', department: 'Facilities', location: 'HQ Floor 3', owner: 'S. Kapoor', updated: 'Yesterday' },
    { id: 'AF-9921', name: 'Office Chair', category: 'Furniture', status: 'Available', department: 'Engineering', location: 'Desk E14', owner: '-', updated: '3h ago' },
    { id: 'AF-9838', name: 'Monitor', category: 'Electronics', status: 'Available', department: 'Engineering', location: 'Desk E15', owner: '-', updated: '3h ago' },
  ],
  bookingResources: [
    { id: 'RES-1', name: 'Conference Room B2', type: 'Room', status: 'Active' },
    { id: 'RES-2', name: 'Projector AF-0062', type: 'Asset', status: 'Active' },
    { id: 'RES-3', name: 'Training Room A1', type: 'Room', status: 'Active' },
  ],
  maintenance: [
    { id: 'MR-101', asset: 'AF-0062', title: 'Projector bulb not turning on', status: 'Pending', assignee: 'Unassigned', date: '2h ago' },
    { id: 'MR-102', asset: 'AF-0031', title: 'AC unit making noise', status: 'Approved', assignee: 'Unassigned', date: '4h ago' },
    { id: 'MR-103', asset: 'AF-0038', title: 'Forklift inspection', status: 'Technician assigned', assignee: 'R. Varma', date: 'Today' },
    { id: 'MR-104', asset: 'AF-0007', title: 'Printer jam', status: 'In progress', assignee: 'S. Kapoor', date: 'Yesterday' },
  ],
  bookings: [
    { id: 'BK-001', resource: 'Conference Room B2', title: 'Procurement team', date: '2026-07-07', start: '9:00', end: '10:00' },
    { id: 'BK-002', resource: 'Conference Room B2', title: 'Design team', date: '2026-07-07', start: '10:30', end: '11:45' },
  ],
  audits: [
    { asset: 'AF-0012', name: 'Dell laptop', location: 'Desk E12', status: 'Verified', note: 'Serial matched' },
    { asset: 'AF-9921', name: 'Office chair', location: 'Desk E14', status: 'Missing', note: 'Not found at desk' },
    { asset: 'AF-9838', name: 'Monitor', location: 'Desk E15', status: 'Damaged', note: 'Panel crack' },
  ],
  transfers: [],
  logs: [
    { type: 'Allocation', title: 'Asset AF-0114 registered', detail: 'MacBook Pro 14', time: '15 min ago', read: false },
    { type: 'Booking', title: 'Booking confirmed', detail: 'Conference Room B2', time: '1h ago', read: false },
    { type: 'Maintenance', title: 'MR-101 moved to Pending', detail: 'Projector bulb', time: '2h ago', read: false },
    { type: 'Alert', title: 'Asset AF-9921 flagged', detail: 'Q3 audit discrepancy', time: '3h ago', read: false },
  ],
};
